POST http://localhost:3000/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkZWVrYTNAbWFpbGluYXRvci5jb20iLCJleHBpcmVkIjoxNzY5NzAzMTk1LCJ1c2VyX2lkIjozfQ.G5T8B6uEdCc28yNWk9zjgFRJ-RTb5uJI1FKENDobAq0

{
    "name": "Test 5 event",
    "description": "Event description bross",
    "location": "test location",
    "dateTime": "2026-01-27T15:30:30.000Z"
}