PUT http://localhost:3000/events/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkZWVrYTNAbWFpbGluYXRvci5jb20iLCJleHBpcmVkIjoxNzY5NzAzMTk1LCJ1c2VyX2lkIjozfQ.G5T8B6uEdCc28yNWk9zjgFRJ-RTb5uJI1FKENDobAq0

{
    "name": "Updated test event",
    "description": "Event description brokk",
    "location": "test location updated",
    "dateTime": "2026-01-27T15:30:30.000Z"
}